server:
  port: 0

spring:
  application:
    name: notification-service

  data:
    redis:
      host: 192.168.5.61
      port: 6379
      timeout: 1000ms

  kafka:
    consumer:
      bootstrap-servers: 192.168.5.61:9092
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: orderCreatedEvent:com.minguccicommerce.common_library.dto.OrderCreatedEvent

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: minguccicommerce-secure-jwt-key-which-is-very-long-32byte
  access-token-expiration: 900000
  refresh-token-expiration: 604800000