# application.yml (payment-service)

server:
  port: 0

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mariadb://192.168.5.61:3306/paymentdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: minguccicommerce-secure-jwt-key-which-is-very-long-32byte
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

toss:
  client-key: test_ck_jExPeJWYVQ4RKWwkW0gv349R5gvN
  secret-key: test_sk_eqRGgYO1r57dEa20ygDO3QnN2Eya