server:
  port: 0

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mariadb://192.168.5.61:3306/userdb
    username: root
    password: 1111
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: minguccicommerce-secure-jwt-key-which-is-very-long-32byte
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

