server:
  port: 0

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mariadb://192.168.5.61:3306/productdb
    username: root
    password: 1111
    driver-class-name: org.mariadb.jdbc.Driver

  kafka:
    bootstrap-servers: 192.168.5.61:9092
    consumer:
      group-id: product-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: orderCreatedEvent:com.minguccicommerce.common_library.dto.OrderCreatedEvent

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  elasticsearch:
    uris: http://localhost:9200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka ?? ??
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"  # actuator? ?? ????/health ??