server:
  port: 0

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mariadb://192.168.5.61:3306/productdb
    username: root
    password: 1111
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  elasticsearch:
    uris: http://localhost:9200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka ?? ??
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"  # actuator? ?? ????/health ??